# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arknightsUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(390, 290)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.centralwidget.setFont(font)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.frame.setStyleSheet("QFrame{background-image: url(:/新前缀/ui_img/background.png);border:none}\n"
"\n"
"QLabel{color:#fff;background:transparent;font-size:14px;font-weight:bold}\n"
"\n"
"QPushButton{border:rgba(255,255,255,0.8);background:rgba(255,255,255,0.7);height:30px;border-radius:4px}\n"
"QPushButton:pressed{background-color:rgba(255,255,255,0.5);}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.hitokotoLable = QtWidgets.QLabel(self.frame)
        self.hitokotoLable.setGeometry(QtCore.QRect(0, 100, 381, 81))
        self.hitokotoLable.setStyleSheet("<--*{background:rgba(255,255,255,0.7);color:rgb(0,0,0);border-radius:10px}!-->")
        self.hitokotoLable.setText("")
        self.hitokotoLable.setAlignment(QtCore.Qt.AlignCenter)
        self.hitokotoLable.setObjectName("hitokotoLable")
        self.logLable = QtWidgets.QLabel(self.frame)
        self.logLable.setGeometry(QtCore.QRect(10, 50, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.logLable.setFont(font)
        self.logLable.setStyleSheet("*{color:black;border-radius:10px;font-size:16px}")
        self.logLable.setText("")
        self.logLable.setAlignment(QtCore.Qt.AlignCenter)
        self.logLable.setObjectName("logLable")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 97, 391, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.widget_3 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_3.setObjectName("widget_3")
        self.autoCountBt = QtWidgets.QPushButton(self.widget_3)
        self.autoCountBt.setGeometry(QtCore.QRect(0, 26, 121, 30))
        self.autoCountBt.setObjectName("autoCountBt")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(0, 6, 101, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit.setGeometry(QtCore.QRect(98, 3, 21, 20))
        self.lineEdit.setStyleSheet("*{border-image:none;\n"
" border:2px solid rgb(100,50,30);background:rgba(255,255,255,0.7);border-radius:4px}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.devConnectBt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.devConnectBt.setObjectName("devConnectBt")
        self.horizontalLayout.addWidget(self.devConnectBt)
        self.stopAllBt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stopAllBt.setObjectName("stopAllBt")
        self.horizontalLayout.addWidget(self.stopAllBt)
        self.startGameBt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startGameBt.setObjectName("startGameBt")
        self.horizontalLayout.addWidget(self.startGameBt)
        self.widget_2 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout.addWidget(self.widget_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.autoFriendsBt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.autoFriendsBt.setObjectName("autoFriendsBt")
        self.horizontalLayout_2.addWidget(self.autoFriendsBt)
        self.expMapBt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.expMapBt.setObjectName("expMapBt")
        self.horizontalLayout_2.addWidget(self.expMapBt)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.autoCountBt.setText(_translate("MainWindow", "自动刷本"))
        self.label.setText(_translate("MainWindow", "指定重复次数"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.devConnectBt.setText(_translate("MainWindow", "连接设备"))
        self.stopAllBt.setText(_translate("MainWindow", "停止"))
        self.startGameBt.setText(_translate("MainWindow", "启动游戏"))
        self.autoFriendsBt.setText(_translate("MainWindow", "好友访问"))
        self.expMapBt.setText(_translate("MainWindow", "开始刷本"))
import ui_rc
